<a href="https://colab.research.google.com/github/nitinmalviya326/deep-learning-lab/blob/main/dl_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# creating 1D array using numpy
a1 = np.array([1, 2, 3])
print(a1.shape)

#creating 2D array using numpy
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
print(a2.shape)

# creating 3D array using numpy
a3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(a3.shape)


(3,)
(2, 3)
(2, 2, 2)


In [5]:
import torch

#creating 1D array using pytorch
t1 = torch.tensor([1, 2, 3])
print(t1.shape)

#creating 2D array using pytorch
t2 = torch.tensor([[1, 2, 3],
                   [4, 5, 6]])
print(t2.shape)

#creating 3D array using pytorch
t3 = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(t3.shape)


torch.Size([3])
torch.Size([2, 3])
torch.Size([2, 2, 2])


In [12]:
# operations using numpy
x = np.array([5, 6, 8])
y = np.array([9, 11, 12])

print("Addition of X and Y =", x + y)
print("substraction of X and Y =", x - y)
print("multiplication of X and Y =", x * y)
print("devision of X and Y =", x / y)



Addition of X and Y = [14 17 20]
substraction of X and Y = [-4 -5 -4]
multiplication of X and Y = [45 66 96]
devision of X and Y = [0.55555556 0.54545455 0.66666667]


In [11]:
# operations using pytorch
x = torch.tensor([5, 6, 8])
y = torch.tensor([9, 11, 12])

print("Addition of X and Y =", x + y)
print("substraction of X and Y =", x - y)
print("multiplication of X and Y =", x * y)
print("devision of X and Y =", x / y)



Addition of X and Y = tensor([14, 17, 20])
substraction of X and Y = tensor([-4, -5, -4])
multiplication of X and Y = tensor([45, 66, 96])
devision of X and Y = tensor([0.5556, 0.5455, 0.6667])


In [17]:
# dot product using numpy
d= np.dot([5, 6, 8], [9, 11, 12])
print("dot product =",d)

#matrix multiplication using numpy
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(" matrix multiplication ",A @ B)


dot product = 207
 matrix multiplication  [[19 22]
 [43 50]]


In [21]:
#  indexing using numpy
a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(a[0, 1])      # 20
print(a[:, 1])      # column
print(a[1, :])      # row


20
[20 50]
[40 50 60]


In [22]:
# indexing using pytorch
t = torch.tensor([[10, 20, 30],
                  [40, 50, 60]])

print(t[0, 1])
print(t[:, 1])


tensor(20)
tensor([20, 50])


In [23]:
#boolean masking using numpy
a = np.array([1, 2, 3, 4, 5])
a[a > 3]


array([4, 5])

In [24]:
# boolean masking using pytorch
t = torch.tensor([1, 2, 3, 4, 5])
t[t > 3]


tensor([4, 5])

In [27]:
# PyTorch: .view(), .reshape(), .unsqueeze(), .squeeze()
t = torch.arange(6)

print(t.view(2, 3))
print(t.reshape(3, 2))
print(t.unsqueeze(0))  # add dimension at index 0
print(t.squeeze())     # remove size-1 dimensions



tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1],
        [2, 3],
        [4, 5]])
tensor([[0, 1, 2, 3, 4, 5]])
tensor([0, 1, 2, 3, 4, 5])


In [28]:
# in place vs out of place
x = torch.tensor([1, 2, 3])
y = x + 1
print(y)

tensor([2, 3, 4])
